/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACarousel: typeof import("@arco-design/web-vue")["Carousel"]
    ACarouselItem: typeof import("@arco-design/web-vue")["CarouselItem"]
    ADoption: typeof import('@arco-design/web-vue')['Doption']
    ADropdown: typeof import('@arco-design/web-vue')['Dropdown']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    APagination: typeof import('@arco-design/web-vue')['Pagination']
    ASkeleton: typeof import('@arco-design/web-vue')['Skeleton']
    ASkeletonLine: typeof import('@arco-design/web-vue')['SkeletonLine']
    ASkeletonShape: typeof import('@arco-design/web-vue')['SkeletonShape']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    DragableResize: typeof import("./src/components/DraggableResize/DraggableResize.vue")["default"]
    DraggableResize: typeof import('./src/components/DraggableResize/DraggableResize.vue')['default']
    KSkeleton: typeof import('./src/components/KSkeleton/KSkeleton.vue')['default']
    KSkeletonItem: typeof import('./src/components/KSkeleton/components/KSkeletonItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skeleton: typeof import("./src/components/KSkeleton/KSkeleton.vue")["default"]
  }
}
